spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: admin
    url: jdbc:mysql://localhost:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
server:
  context-path: /sell

wechat:
  mpAppId: wxdc42cb0d1f214624 #这是申请的测试账号的appid，自己公司服务号有这个信息
  mpAppSecret: f06c09dc913e3a6a2eea0ef1d0f51110 #这是申请的测试账号的Secret，自己公司服务号有这个信息
  openAppId: wxxdc42cb0d1f214624
  openAppSecret: fx06c09dc913e3a6a2eea0ef1d0f51110
  mchId: 151515
  mchKey: 15151515
  keyPath: /var/weixin_cert/apiclient_cert.p12 #这里填写我们下载下来的证书存放的位置,微信退款需要用到证书
  notifyUrl: https://www.xxxx.com/sell/pay/notify #需要写处理 notify 请求的controller来处理异步通知

projectUrl:
  wechatMpAuthorize: http://cja5at.natappfree.cc
  wechatOpenAuthorize: http://cja5at.natappfree.cc
  sell: